### ISSUE TITLE
Analysis of Existing Source of EDA tools in Python

### ISSUE THREAD

**Issue by navjotsingh151** [navjotsingh151/SimpliViz#2]
This is the Parent Issue tracking the Below issues:

- [ ] Zeppline Analysis - Parent of #1 
- [ ] Databricks Analysis - Parent of #3 
- [ ] AutoViz Analysis - Parent of #4
